name: main

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: execute py script
        run: python main.py
      - name: commit files
        if: env.SHOULD_COMMIT == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
